### ISSUE TITLE
Love this theme. Dark Mode Coming?

### ISSUE THREAD

**Issue by rifen** [negrel/hugo-theme-pico#14]
The white is burning my eyes :) Just wanted to see if this is actively being developed! Or if I need to implement a workaround of sorts.

**Comment by negrel** [comment]
I'm glad you enjoyed the theme. I'm currently working on other projects but I will add a dark mode for this theme soon or later.
If you decide to implement it yourself, a merge request would be greatly appreciated.

**Comment by negrel** [comment]
Dark mode support added in 8965487d66afe78ce73eba972e5362be26a9caca :)
