### ISSUE TITLE
Something Changed

### ISSUE THREAD

**Issue by rifen** [negrel/hugo-theme-pico#16]
**First I thought I'd start with I appreciate the work even though you had said you were working on other things which I totally get!**

Tried implementing darkMode and then kind of got into the weeds of things. Well the dark mode portion didn't work (Added `darkMode = true` and updated the git submodule) I see `<html lang="en-us" class=" dark ">` but nothing is dark.

So I went back to look at my config.toml and noticed I had commented for some reason(compared to the one on the exampleSite):
`
[params]
 customCSS = ["style/style.css", "style/theme.sass"] # Path relative to assets folder
 customJS = ["js/console.js"] # Path relative to assets folder
`
_Uncommented that and all hell broke loose pretty much._

Commented it back and darkMode still doesn't work. I could be looking at this wrong but I do see this in my html:

Got the same error pretty much with everything...Netlify, hugo server, hugo server --themeDir ../..
Error:
```
Building sites … ERROR 2021/01/29 17:04:03 render of "page" failed: execute of template failed: template: blog/single.html:6:4: executing "blog/single.html" at <partial "head/css.html" .>: error calling partial: ".../themes/pico/exampleSite/themes/pico/layouts/partials/head/css.html:9:96": execute of template failed: template: partials/head/css.html:9:96: executing "partials/head/css.html" at <resources>: can't evaluate field PostProcess in type interface {}
ERROR 2021/01/29 17:04:03 render of "section" failed: execute of template failed: template: blog/list.html:6:4: executing "blog/list.html" at <partial "head/css.html" .>: error calling partial: ".../themes/pico/exampleSite/themes/pico/layouts/partials/head/css.html:9:96": execute of template failed: template: partials/head/css.html:9:96: executing "partials/head/css.html" at <resources>: can't evaluate field PostProcess in type interface {}
ERROR 2021/01/29 17:04:03 render of "home" failed: execute of template failed: template: index.html:6:4: executing "index.html" at <partial "head/css.html" .>: error calling partial: ".../themes/pico/exampleSite/themes/pico/layouts/partials/head/css.html:9:96": execute of template failed: template: partials/head/css.html:9:96: executing "partials/head/css.html" at <resources>: can't evaluate field PostProcess in type interface {}
ERROR 2021/01/29 17:04:03 render of "taxonomyTerm" failed: execute of template failed: template: taxonomy/list.html:6:4: executing "taxonomy/list.html" at <partial "head/css.html" .>: error calling partial: ".../themes/pico/exampleSite/themes/pico/layouts/partials/head/css.html:9:96": execute of template failed: template: partials/head/css.html:9:96: executing "partials/head/css.html" at <resources>: can't evaluate field PostProcess in type interface {}
Total in 24 ms
Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: blog/single.html:6:4: executing "blog/single.html" at <partial "head/css.html" .>: error calling partial: ".../themes/pico/exampleSite/themes/pico/layouts/partials/head/css.html:9:96": execute of template failed: template: partials/head/css.html:9:96: executing "partials/head/css.html" at <resources>: can't evaluate field PostProcess in type interface {}
```

My repo: [https://github.com/rifen/sethg.info](https://github.com/rifen/sethg.info)

**Comment by negrel** [comment]
First of all, thanks for your feedback.
The darkmode didn't work because you didn't update Hugo's resources (`resources/` folder), I updated the [`update.sh`](https://raw.githubusercontent.com/negrel/hugo-theme-pico/master/exampleSite/update.sh) script so it can be done automatically. Another solution is to install the extended version of Hugo with `postcss-cli` and regenerate the resources (exampleSite use it to compile the custom SASS files).

The second error is simply due to the absence of the `css` and `js` files that are present in the exampleSite (under `assets/`).

**Comment by rifen** [comment]
Hm so I tried updating the `resources` folder by running `update.sh` after fixing it and that didn't change the error. I deleted the resources folder completely and regenerated it and nothing.

I have the extended version of Hugo installed and tried installing all sorts of npm packages and still no dice. 
`npm install postcss-cli, postcss-import, autoprefixer, @fullhuman/postcss-purgecss, tailwindcss` then deleted resources and then tried `hugo server -D`
Tried clearing my Netlify cache to see if maybe something was stuck and that didn't change anything. 

I don't need to move the `assets/` folder into my site right? It just goes and finds it in the theme git submodule. 

Still getting the same thing and I am seeing `assets` files in exampleSite 🤔 

Lol I feel like I am doing nothing wrong but who knows 🤷‍♂️ 

I did end up getting the exampleSite to work but my website won't do the same.

**Comment by negrel** [comment]
To fix the second error you must either empty the `customCSS` and `customJS` arrays or comment them so Hugo won't search for non-existing file (that exist in `exampleSite/assets` but **not** for the theme in `pico/assets`).
You don't need the assets folder for you site since you are not importing custom assets.

The following work for your repo:
```shell
git clone https://github.com/rifen/sethg.info.git && cd sethg.info

# The version of the repo of yesterday
git checkout c8c73c2bc2d6f3d917d38f0a0c51aa7307fb3050

# Init the submodule (the theme)
git submodule update --init

cd sethg
# Run the update script
. ./themes/pico/exampleSite/update.sh

# Start the dev server
hugo server
```

**Comment by rifen** [comment]
Steps taken:
`rm -rf sethg.info` # Deleted my current directory

`git clone https://github.com/rifen/sethg.info.git && cd sethg.info`

`git checkout c8c73c2bc2d6f3d917d38f0a0c51aa7307fb3050`

`git submodule update --init`

`cd sethg`

`. ./themes/pico/exampleSite/update.sh`

```
Updating node modules :
npx npm-check-updates -u && npm install
npx: installed 318 in 27.204s
No package.json

Please add a package.json to the current directory, specify the --packageFile or --packageData options, or pipe a package.json to stdin.
Updating Pico submodule :
git submodule foreach git pull origin master
Entering 'themes/pico'
From https://github.com/negrel/hugo-theme-pico
 * branch            master     -> FETCH_HEAD
Updating 63a62f9..b8fce34
Fast-forward
 README.md                                                                   |      5 +-
 assets/sass/_theme.sass                                                     |      1 -
 exampleSite/config.toml                                                     |      2 +-
 .../assets/sass/sass/styles.sass_b8e3badeabeea89cef291c07b224cc39.content   | 252451 +++++++++++++++++++++------------
 exampleSite/update.sh                                                       |     45 +-
 layouts/partials/widgets/hero.html                                          |      2 +-
 static/favicon.ico                                                          |    Bin 0 -> 13742 bytes
 7 files changed, 162457 insertions(+), 90049 deletions(-)
 create mode 100644 static/favicon.ico
 ```
 
 New Error:
 
 ```
 33s ~/.../sethg.info/sethg (c8c73c2 !) > hugo server                                                            8:19:53
Building sites … ERROR 2021/01/31 08:20:13 render of "taxonomy" failed: "/home/rifen/Projects/sethg.info/sethg/themes/pico/layouts/taxonomy/list.html:21:38": execute of template failed: template: taxonomy/list.html:21:38: executing "main" at <$otherTags.Values>: can't evaluate field Values in type *maps.Scratch
ERROR 2021/01/31 08:20:13 render of "taxonomyTerm" failed: "/home/rifen/Projects/sethg.info/sethg/themes/pico/layouts/taxonomy/list.html:21:38": execute of template failed: template: taxonomy/list.html:21:38: executing "main" at <$otherTags.Values>: can't evaluate field Values in type *maps.Scratch
Built in 235 ms
Error: Error building site: failed to render pages: render of "taxonomyTerm" failed: "/home/rifen/Projects/sethg.info/sethg/themes/pico/layouts/taxonomy/list.html:21:38": execute of template failed: template: taxonomy/list.html:21:38: executing "main" at <$otherTags.Values>: can't evaluate field Values in type *maps.Scratch
```
Looks like the error has changed to be `taxonomy/lists.html' specific now.

`rm -rf resources`

`hugo server`

same error.

**Comment by negrel** [comment]
I had the same issue with a previous hugo version. What is your Hugo version ? Could you try with the latest version ?

**Comment by rifen** [comment]
Netlify: `8:52:04 AM: Hugo Static Site Generator v0.80.0-792EF0F4/extended linux/amd64 BuildDate: 2020-12-31T13:46:18Z`

Local: `Hugo Static Site Generator v0.80.0-792EF0F4/extended linux/amd64 BuildDate: 2020-12-31T13:46:18Z`

Looks like the latest version to me 🤔 

So looking at it further it could be a dependency issue locally but remotely I would think it should work fine because everything is fresh in the beginning and netlify goes to find your package.json and installs the dependencies you list.

**Comment by rifen** [comment]
Let me go through everything fresh again and see if I can get something going for us here...

**Comment by negrel** [comment]
Could you try with [this repo](https://github.com/negrel/sethg.info) ?

**Comment by rifen** [comment]
I got this:
```
~/.../sethg.info/sethg (main) > hugo server -D                                                                 21:29:48
Start building sites …
Built in 3226 ms
Error: Error building site: POSTCSS: failed to transform "css/main.css" (text/css): Error: Cannot find module '@fullhuman/postcss-purgecss'
Require stack:
- /home/rifen/Projects/sethg.info/sethg/themes/pico/assets/config/postcss.config.js
- /usr/local/lib/node_modules/postcss-cli/node_modules/cosmiconfig/dist/loaders.js
- /usr/local/lib/node_modules/postcss-cli/node_modules/cosmiconfig/dist/ExplorerBase.js
- /usr/local/lib/node_modules/postcss-cli/node_modules/cosmiconfig/dist/Explorer.js
- /usr/local/lib/node_modules/postcss-cli/node_modules/cosmiconfig/dist/index.js
- /usr/local/lib/node_modules/postcss-cli/node_modules/postcss-load-config/src/index.js
- /usr/local/lib/node_modules/postcss-cli/index.js
- /usr/local/lib/node_modules/postcss-cli/bin/postcss
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/rifen/Projects/sethg.info/sethg/themes/pico/assets/config/postcss.config.js:5:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/rifen/Projects/sethg.info/sethg/themes/pico/assets/config/postcss.config.js',
    '/usr/local/lib/node_modules/postcss-cli/node_modules/cosmiconfig/dist/loaders.js',
    '/usr/local/lib/node_modules/postcss-cli/node_modules/cosmiconfig/dist/ExplorerBase.js',
    '/usr/local/lib/node_modules/postcss-cli/node_modules/cosmiconfig/dist/Explorer.js',
    '/usr/local/lib/node_modules/postcss-cli/node_modules/cosmiconfig/dist/index.js',
    '/usr/local/lib/node_modules/postcss-cli/node_modules/postcss-load-config/src/index.js',
    '/usr/local/lib/node_modules/postcss-cli/index.js',
    '/usr/local/lib/node_modules/postcss-cli/bin/postcss'
  ]
}
```
I believe I have fixed this before by installing npm modules locally so I navigated to `themes/pico` and ran `npm install` and it worked. As well got dark mode to work and everything. Tell me your secrets :)

I haven't tried it in netlify yet though. I assume it will work there as well.

**Comment by negrel** [comment]
You shouldn't need to install any module to use the theme.
I've added a Dockerfile in the [forked repository of your site](https://github.com/negrel/sethg.info) that setup and start the hugo server. It seems to work in a clean environment, I don't what I do except recommanding you to compare the Dockerfile with your configuration : /
