### ISSUE TITLE
How to switch between dark theme and light theme

### ISSUE THREAD

**Issue by haxifang-aircos** [negrel/hugo-theme-pico#19]
I have successfully installed the theme and I like it very much, but I don’t know how to switch between dark and light modes flexibly. I have been using dark mode.

**Comment by negrel** [comment]
Currently, the darkmode is either fully enabled or disabled. I'm planning to add the option to choose between the full mode light, full mode dark and an adaptative mode based on the browser preferences.

**Comment by negrel** [comment]
I just added the adaptative mode 58ed5324022ab099df2aef9695412f4dcb4ac66c. If you update your theme and comment `darkmode` option and regenerate your website, the theme will adapth the theme based on the browser preferences

**Comment by haxifang-aircos** [comment]
> 我刚刚添加了自适应模式[58ed532](https://github.com/negrel/hugo-theme-pico/commit/58ed5324022ab099df2aef9695412f4dcb4ac66c)。如果您更新主题和评论`darkmode`选项并重新生成网站，则该主题将根据浏览器首选项来适应主题

Thank you for your reply
