### ISSUE TITLE
Build Result Differ than Development Result

### ISSUE THREAD

**Issue by nalakawula** [negrel/hugo-theme-pico#22]
When I run `hugo server` the site is work as expected.

But when I run `hugo --gc` the result is differ:
![image](https://user-images.githubusercontent.com/8051577/108178003-821c5680-7136-11eb-9afa-a71f16be58dc.png)

How I build?
```
hugo -v
INFO 2021/02/17 15:42:41 Using config file: 
Start building sites … 
INFO 2021/02/17 15:42:41 syncing static files to /home/sumar/Repositories/gula/public/
INFO 2021/02/17 15:42:41 postcss: use config file /home/sumar/Repositories/gula/themes/pico/assets/config/postcss.config.js

                   | ID  
-------------------+-----
  Pages            | 22  
  Paginator pages  |  0  
  Non-page files   |  0  
  Static files     | 40  
  Processed images |  0  
  Aliases          |  2  
  Sitemaps         |  1  
  Cleaned          |  0  

Total in 10069 ms
```

Any advice?

Thanks

**Comment by negrel** [comment]
I've never encountered this issue, could you provide the following information:
- what differ from the dev site
- your Hugo version
- a repo to reproduce the issue

Thanks
