### ISSUE TITLE
Getting rid of contact form

### ISSUE THREAD

**Issue by Pshemas** [negrel/hugo-theme-pico#38]
I'm trying to get rid of the contact form and have a "mailto:sample@domain.com" type of link.
Tried to modify this section:
```
[[menu.main]]
identifier = "contact" # identifier is use for translations
pre = "" # pre is inserted before the translation (icons, image, etc)
url = "/#contact" 
weight = 30
```

by changing url part to "mailto:sample@domain.com" but that's wrong I get "domainname/mailto:sample@domain.com".
What's the proper way to add links to the top menu?

**Comment by negrel** [comment]
This configuration section configure the top right corner menu. The URL correspond to the anchor URL. If you want to edit the contact form you must edit the according widget.
If you want to edit the contact form, you can use the `contact.md` of the example site as a base and edit it.
