### ISSUE TITLE
script doesn't work

### ISSUE THREAD

**Issue by DongHyun99** [negrel/hugo-theme-pico#40]
Hi. I'm a student writing your theme in Korea. I'm using it really well.

I want to add an literacy script to this theme and add a comment function. But the script doesn't work. So I want to ask if there is a solution.

```
<script src="https://utteranc.es/client.js"
        repo="DongHyun99/Web_Comment"
        issue-term="pathname"
        theme="github-light"
        crossorigin="anonymous"
        async>
</script>
```

Thank you for making a good theme!

**Comment by negrel** [comment]
Hello,
Custom script tag are not supported as of today. You can only add custom script in assets/ folder as in the example site.
If you really need it, you can contribute or wait until I implement it when I will have free time.

**Comment by DongHyun99** [comment]
Ok thank you for answering.
