### ISSUE TITLE
A Couple of Questions

### ISSUE THREAD

**Issue by SamGreenwood1** [negrel/hugo-theme-pico#45]
- How would I add a link to an external site to the nav menu?
- Does this theme support having pure HTML pages instead of Markdown?
- How do you get the contact form to render properly?

**Comment by negrel** [comment]
You can answer those questions by looking at the README and Hugo's documentation or theme sources. Issues aren't designed to ask questions

**Comment by SamGreenwood1** [comment]
To clarify, are those features supported by the theme? I understand that issues aren't designed for conversations like this, but how do you suggest I do this? There is no discussions tab on this repo.

**Comment by SamGreenwood1** [comment]
Also, I need help with the icons in the social buttons in the footer not showing up. The buttons themselves are there, but the icons don't show up,

**Comment by SamGreenwood1** [comment]
Also, I need help with the icons in the social buttons in the footer not showing up. The buttons themselves are there, but the icons don't show up, @negrel
