### ISSUE TITLE
Getting a Error 403 Forbidden

### ISSUE THREAD

**Issue by SamGreenwood1** [negrel/hugo-theme-pico#46]
I somehow lost my website files a couple of days ago. I recreated the site today and installed this theme, and am getting error 403 whenever I go to the site.

**Comment by negrel** [comment]
It has nothing to do with the theme. This theme is for Hugo which is a static site generator. 403 is returned by the web server you're using

**Comment by SamGreenwood1** [comment]
I fixed it anyway
